- hosts: all
  become: yes
  roles:
    - base
    - geerlingguy.docker
    - role: viasite-ansible.zsh
      zsh_antigen_bundles_extras:
        - nvm
        - joel-porquet/zsh-dircolors-solarized
      zsh_autosuggestions_bind_key: "^U"
      zsh_user: "{{ lookup('env', 'USER') }}"
    - vscode
    - role: 1password
      non_root_user: "{{ lookup('env', 'USER') }}"
    - misc
- hosts: all
  become: false # NVM should be installed as your regular user
  roles:
    - role: morgangraphics.ansible_role_nvm
      nvm_user: "{{ lookup('env', 'USER') }}"
    - role: git_config
      git_user_name: "Hermann Björgvin Haraldsson"
      git_user_email: "hermann@hermann.is"
